### PR TITLE
fixed bower.json dependency names to be the common uses

### PR DESCRIPTION
**Pull request by christrude**
Please allow this pull request to go through. Causing a lot of problems at build time with grunt package injection with duplicity of components.

### CODE REVIEW

**Comment by boneskull** [comment]
`bootstrap-css` will be eliminated (at some point).  Using `bootstrap` proper pulls in a bunch of JavaScript files we don't need.  I'm not sure why you need it or are using it alongside `ui-bootstrap`.

I would accept this PR with line 9 reverted.

**Comment by christrude** [comment]
See that'd be great if bootstrap-css as a dependency only pulled the css
files, but it doesn't, it pulls basically the bootstrap dist folder. The
problem with this is that most people are already including bootstrap, and
this creates a second dependency as bootstrap-css, bloating the asset
stack, and if you use grunt-bower-install in your build scheme, it will put
multiple instances of bootstrap file dependencies in the index.html file.
It' just causing duplicates. I see what you mean though. You don't have to
accept it.

**Comment by boneskull** [comment]
If "most people" are including all of `bootstrap` just to use `ui-bootstrap`, most people are doing it wrong.

Especially when using `grunt-wiredep` (which is either the successor to `grunt-bower-install` or just a rename; not sure)--this will include `bootstrap.js` in your HTML.

You're right about `bootstrap-css`.  A better package would be `bootstrap-css-only`, I imagine.  

Regardless, I'm going to eliminate any "css" dependencies from this package (at some point) or someone can help me do it.

**Comment by boneskull** [comment]
I'm going to close this if you don't wish to make the requested change.  Thanks!

**Pull request closed without merging**
